### ISSUE TITLE
Provision attempt returns incompatible .mpy file

### ISSUE THREAD

**Issue by Konshu** [ANDnXOR/ANDnXOR_DC30_Badge#2]
While attempting to provision after minor changes to chomper_config.py the following error occurs:

`main.py 308 bytes
### Updating from Firebase ###
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib_update.py", line 3, in <module>
  File "chomper_wifi.py", line 2, in <module>
ValueError: incompatible .mpy file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib_update.py", line 3, in <module>
  File "chomper_wifi.py", line 2, in <module>
ValueError: incompatible .mpy file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib_update.py", line 3, in <module>
  File "chomper_wifi.py", line 2, in <module>
ValueError: incompatible .mpy file
`

--

- IDF version: idf4.2
- Modified: Name in chomper_config.py

**Comment by Konshu** [comment]
Side note: While modification of config.json does result in working changes, is it not the intent to modify chomper_config.py for more rolling defaults? I assume that if config.json fails in some manner it just recovers to using the settings within chomper_config.py or rather chomper_config.mpy.
